---
title: "CV"
---

## Short CV

| Employment | |
| --- | --- |
| Since June 2024 | Reader in probability, University of Bath. |
| Dec 2018 - May 2024 |  Senior Lecturer in probability,  University of Bath.|
| Sep 2016 - Nov 2018 | Lecturer in probability,  University of Bath. |
| Oct 2013 - Aug 2016 |   Juniorprofessor in probability theory,  Westf&auml;lische Wilhelms-Universit&auml;t M&uuml;nster. |
|  April 2011 - Sep 2013 |  Postdoc (Wissenschaftlicher Mitarbeiter) at Technische Universit&auml; Berlin in the group of Jochen Blath. |
| Oct 2009 - March 2011 |  Postdoc based at Technische Universit&auml;t Berlin, as part of IRTG Berlin -- Zurich ``Stochastic Models of Complex Processes''. |

| PhD | |
| --- | --- |
| 2006 - 2009 | PhD: ``Stochastic Processes in Random Environment'' under the supervision of Peter M&ouml;rters, Bath |

## Grants

| Grants (as PI) | |
| --- | --- |
| Mar 2024 -- Feb 2027 | 3 year postdoctoral position, `Interplay between geometry and randomness in fitness landscapes for expanding populations' funded by EPSRC, with CoI Matt Roberts. |
| Jan 2016 --  Dec 2018 | 3 year postdoctoral position, grant OR 310/1-1 within the DFG Priority Programme SPP 1590 ``Probabilistic Structures in Evolution'' |


| Grants (as CoI) | | 
| --- | --- |
| 2016 -- 2019 | DFG Network ``Cumulants, concentration and superconcentration''.  |
| March 2013 -- 2015 |  2 year postdoctoral position, grant BL 1105/4-1 within the DFG Priority Programme SPP 1590 “Probabilistic Structures in Evolution” (with J. Blath (PI) and  N. Kurt (CoI)) |




