---
title: "Welcome"
---

<h2 id="publications">Publications</h2>

<h3>Books</h3>

<ul>
  <li><a href="https://link.springer.com/book/10.1007/978-3-031-88115-2">Stochastische Modelle der Versicherungsmathematik.</a>
<br>with Jochen Blath and Michael Scheutzow. Mathematik Kompakt. Birkh&auml;user, 2025 </li>
</ul>

<h3>Preprints</h3>

<ol reversed start="32">
<li><a href="https://arxiv.org/pdf/2607.14950">Emergence of polymorphism in stochastic evolutionary games
</a> <br>
with  <b>Bill Nunn</b> and <b>Tim Rogers</b>. Preprint, <a href="https://arxiv.org/abs/2607.14950">arXiv:2607.14950</a>,
17 July 2026.</li>
<li><a href="https://arxiv.org/pdf/2607.12920">Balancing innovation and assimilation in research communities
</a> <br>
with  <b>Bill Nunn</b>, <b>Maria Horner</b> and <b>Tim Rogers</b>. Preprint, <a href="https://arxiv.org/abs/2607.12920">arXiv:2607.12920</a>,
16 July 2026.</li>
<li><a href="https://arxiv.org/pdf/2607.12864">Can deleterious mutations surf deterministic population waves?</a> <br>
with <b>João Luiz de Oliveira Madeira</b> and <b>Sarah Penington</b>. Preprint, <a href="https://arxiv.org/abs/2607.12864">arXiv:2607.12864</a>,
16 July 2026.</li>
		<li><a href="https://arxiv.org/pdf/2603.29442">A compact support property for infinite-dimensional SDEs with Hölder continuous coefficients.</a> <br>
with <b>Thomas Hughes</b>. Preprint, <a href="https://arxiv.org/abs/2603.29442">arXiv:2603.294428</a>,
31 Mar 2026.</li>
<li><a href="https://arxiv.org/pdf/2603.06478">A functional law of large numbers for a spatial model of Muller's ratchet.</a> <br>
with <b>João Luiz de Oliveira Madeira</b> and <b>Sarah Penington</b>. Preprint, <a href="https://arxiv.org/abs/2603.06478">arXiv:2603.06478</a>,
17 July 2026.</li>
<li><a href="https://arxiv.org/abs/2603.06468">Existence, uniqueness and moment bounds for a spatial model of Muller's ratchet.</a> <br>
with <b>João Luiz de Oliveira Madeira</b> and <b>Sarah Penington</b>. Preprint, <a href="https://arxiv.org/abs/2603.06468">arXiv:2603.06468</a>,
09 Mar 2026.</li>
<li><a href="http://arxiv.org/pdf/1508.07826">The infinite rate symbiotic branching model: from discrete to continuous space. </a><br>
with <b>Matthias Hammer</b>. Preprint <a href="http://arxiv.org/abs/1508.07826">arXiv:1508.07826</a>, 2015.</li>
</ol> 

<h3>In Press</h3>
<ol reversed start="25">
        <li><a href="https://arxiv.org/pdf/2404.13730">Cluster sizes in subcritical soft Boolean models.</a><br>
        with <b>Benedikt Jahnel</b> and <b>Lukas L&uuml;chtrath</b>. To appear in <i>Annals of Applied Probability</i>, <a href="https://arxiv.org/abs/2404.13730">arXiv:2404.13730</a>, accepted 9 June 2026.</li> 

            <li><a href="https://arxiv.org/pdf/2110.14537.pdf">The contact process with fitness on random trees.</a><br>
with <b>Natalia Cardona-Tobón</b>. To appear in <i>Advances in Applied Probability</i>, <a href="https://arxiv.org/abs/2110.14537">arXiv:2110.14537</a>, accepted May 2026.</li> 

    <li><a href="https://www.e-publications.org/ims/submission/AIHP/user/submissionFile/65498?confirm=94487abf">The contact process on dynamical random trees with degree dependence.</a><br>
        with <b>Natalia Cardona-Tobón</b>, <b>Marco Seiler</b> and <b>Anja Sturm</b>. To appear in <i><a href="https://www.imstat.org/journals-and-publications/annales-de-linstitut-henri-poincare/">Annales de l'Institut Henri Poincar&eacute;: Probab. et Stat.</a></i>, accepted Feb 2026.</li> 

     
    
</ol>


<h3>Publications</h3>



<ol reversed>
<li><a href="https://www.sciencedirect.com/science/article/pii/S0304414925000377">The Contact Process on a Graph Adapting to the Infection.</a><br>
        with <b>John Fernley</b> and <b>Peter M&ouml;rters</b>. <i>Stochastic Processes and Applications</i> Volume 183, 104596, May 2025.</li>
<li><a href="https://projecteuclid.org/journals/annals-of-applied-probability/volume-34/issue-4/The-maximal-degree-in-random-recursive-graphs-with-random-weights/10.1214/23-AAP2041.full">The maximal degree in random recursive graphs with random weights.
</a><br>
with <b>Bas Lodewijks</b>. <i>Annals of Applied Probability</i>, 34(4): 3469-3540, 2024.</li>    
<li><a href="https://www.sciencedirect.com/science/article/pii/S0304414923000212">Fine asymptotics for the maximum degree in weighted recursive trees with bounded random weights.
</a><br>
with <b>Laura Eslava</b> and <b>Bas Lodewijks</b>. <i>Stochastic Processes and Applications</i> 158, 505 - 569, 2023.</li>
<li><a href="https://onlinelibrary.wiley.com/doi/epdf/10.1002/rsa.21107">Voter models on subcritical scale-free random graphs</a>.<br>
with <b>John Fernley</b>. <i>Random Structures and Algorithms</i>, 62(2), 376 - 429, 2023</li> <!-- <a href="https://arxiv.org/abs/1911.13187">arXiv:1911.13187</a> -->
<li><a href="https://arxiv.org/pdf/2002.02825">The symbiotic branching model: duality and interfaces</a>.<br>
with <b>Jochen Blath</b>. <!--<a href="https://arxiv.org/abs/2002.02825">arXiv:2002.02825</a>, -->
In <a href="https://www.ems-ph.org/books/book.php?proj_nr=264">"Probabilistic Structures in Evolution"</a>
(E. Baake and A. Wakolbinger, eds.), pp. 311-336, EMS Press, Berlin, 2021.
<li><a href="https://arxiv.org/pdf/1801.06197"> Entrance laws for annihilating Brownian motions and the continuous-space voter model.</a><br>
with <b>Matthias Hammer</b> and <b>Florian V&ouml;llering</b>. <br><i><a href="https://www.sciencedirect.com/science/article/pii/S0304414921000028">Stochastic Processes and their Applications</a></i>, 34, 240-264, 2021.</li>
<li><a href="https://projecteuclid.org/euclid.ejp/1608260520">A phase transition for preferential attachment models with additive fitness</a>.<br>
with <b>Bas Lodewijks</b>. <i>Electronic Journal of Probability</i>, 25, Paper No. 146, 2020.</li>
<li><a href="https://arxiv.org/pdf/1805.01341"> Fluctuations in a general preferential attachment model via Stein's method.</a><br>
with <b>Carina Betken</b> and <b>Hanna D&ouml;ring</b>. <i><a href="https://onlinelibrary.wiley.com/doi/10.1002/rsa.20852">Random Structures & Algorithms</a></i>, 55(4), 808-830, 2019.</li>
<li><a href="https://arxiv.org/pdf/1712.00400">Near critical preferential attachment networks have small giant components.</a><br>
with <b>Maren Eckhoff</b> and <b>Peter M&ouml;rters</b>. <i>Journal of Statistical Physics</i>, 
173(3), 663-703, 2018.</li>
<li><a href="docs/CM_FPP_rev.pdf">Local neighbourhoods for first-passage percolation on the configuration model.</a><br>
with <b>Steffen Dereich</b>. <i>Journal of Statistical Physics</i>, 173(3-4), 485-501, 2018.</li>
<li><a href="docs/AOP1240.pdf"> A new look at duality for the symbiotic branching model. </a><br>
with <b>Matthias Hammer</b> and <b>Florian V&ouml;llering</b>. <i><a href="https://www.imstat.org/journals-and-publications/annals-of-probability/">Annals of Probability</a></i>, 46(5), 2800-2862, 2018. 
<!-- <a href="http://arxiv.org/abs/1509.00354">arXiv:1509.00354</a>, 2017 <br>(Major update: 09/16).--></li>
 <li><a href="docs/AIHP839.pdf">Scaling limit and ageing for branching random walk in Pareto environment. </a><br>
with <b>Matthew I. Roberts</b>. <i><a href="https://www.imstat.org/journals-and-publications/annales-de-linstitut-henri-poincare/">Annales de l'Institut Henri Poincar&eacute;: Probab. et Stat.</a></i> 54(3), 1291-1313, 2018.
<!--<a href="http://arxiv.org/abs/1602.08997">arXiv:1602.08997</a>, 2017.-->
</li>
<li><a href="http://projecteuclid.org/euclid.ejp/1484622023"> One-point localization for branching random walk in Pareto environment. </a><br>
with <b>Matthew I. Roberts</b>. <i><a href="http://projecteuclid.org/euclid.ejp">Electronic Journal of Probability,</a></i>
22, paper no. 6, 2017.
<li>	
<a href="docs/AOP1021.pdf"> Intermittency for branching random walk in Pareto environment </a><br>
with <b>Matthew I. Roberts</b>. <i><a href="http://www.imstat.org/aop/">Annals of Probability</a></i>, 44(3):  2198-2263, 2016. 
<!--[<a href="http://arxiv.org/abs/1405.5449">Preprint@arXiv:1405.5449</a>]</li>-->
<li>	
<!--<a href="http://wwwmath.uni-muenster.de/statistik/ortgiese/Publikationen/docs/interface_SBM.pdf">-->
<!--<a href="http://projecteuclid.org/euclid.aop/1457960384">-->
<a href="docs/AOP989.pdf">
The scaling limit of the interface of the continuous-space
symbiotic branching model</a><br>
with <b>Jochen Blath</b> and <b>Matthias Hammer</b>. <i><a href="http://www.imstat.org/aop/">Annals of Probability</a></i>, 
 44(2): 807-866, 2016. <!--[<a href="http://arxiv.org/abs/1312.2870">Preprint@arXiv:1312.2870</a>]-->
 </li>


<li>	
<a href="http://www.sciencedirect.com/science/article/pii/S0040580914000781">The largest strongly connected component in the cyclical  pedigree model of Wakeley et al.</a><br>
with <b>Jochen Blath</b> and <b>Stephan Kadow</b>.  
<i>Theoretical Population Biology</i>, 98: 28-37, 2014. [<a href="http://arxiv.org/abs/1405.7276">Prepint@arXiv:1405.7276</a>]</li>


<li>
<a href="docs/PA_fitness_BE.pdf">Robust analysis of preferential
    attachment models with fitness</a><br>
with <b>Steffen Dereich</b>. <i><a href="http://journals.cambridge.org/action/displayJournal?jid=CPC">Combinatorics, Probability and Computing</a></i>,
 23 (03):  386-411, 2014.
<!--<a href="http://arxiv.org/abs/1302.3385">arXiv:1302.3385</a>, 2013.-->
</li>


<!-- <li>Tom Alberts and Marcel Ortgiese<br>-->
<!--<a href="docs/critical_window.pdf">-->
<li><a href="http://ejp.ejpecp.org/article/view/2036">The near-critical scaling window for directed polymers on disordered trees</a><br>
with <b>Tom Alberts</b>.
<i>Electronic Journal of Probability</i>, 18, Article 19, 2013.
<!--<a href="http://arxiv.org/abs/1205.0737">arXiv:1205.0737</a></i>--></li>

<li>
<a href="docs/markovchains.pdf">Moments of recurrence times for Markov chains</a><br>
with  <b> Frank Aurzada, Hanna D&ouml;ring, Michael Scheutzow</b>. <i><a href="http://www.math.washington.edu/~ejpecp/ECP/viewarticle.php?id=2296&layout=abstract">Electronic Communications in Probability</a></i>, 16:296-303, 2011.</li>


<li>
<a href="docs/AIHP394.pdf">Ageing in the parabolic Anderson model</a><br>
with <b>Peter M&ouml;rters, Nadia Sidorova</b>. <i><a href="http://www.imstat.org/aihp/">Annales de l'Institut Henri Poincar&eacute;: Probab. et Stat.</a></i>, 47(4): 969-1000, 2011.<!--(version of 29 October 2009)--> <br>
<div class=small>[<a href="http://arxiv.org/abs/0910.5613">Preprint@arXiv:0910.5613</a>] [Supplement: <a href="http://www.math.tu-berlin.de/~ortgiese/docs/animation_ageing.pdf">Animation of limiting process</a>]</div></li>


<li>
<a class="external-link" 	href="docs/polymers_on_trees.pdf">Minimal supporting subtrees for the free energy of polymers on disordered trees</a><br>
with <b>Peter M&ouml;rters</b>. <i>Journal of Mathematical Physics</i>  49,  2008 <a class="external-link" href="http://link.aip.org/link/?JMP/49/125203">(abstract)</a>. </li><!-- (version of 20/06/08) -->


<li>
<a class="external-link" href="docs/BEJ107.pdf">Small value probabilities via the branching tree heuristic</a><br>
with <b>Peter M&ouml;rters</b>. <i><a class="external-link" href="http://www.bernoulli-society.org/index.php/publications/bernoulli-journal/bernoulli-journal">Bernoulli</a></i>, 14(1): 277-299, 2008. </li>


</ol>

  

<h3>Translation</h3>
<ul>
<li><b>Hans-Otto Georgii.</b> <a class="external-link" href="http://www.mathematik.uni-muenchen.de/~georgii/GiiStoch/giistoch_en.php">Stochastics. Introduction to probability and statistics.</a> Translated from the 2007 3rd German edition by Marcel Ortgiese, Ellen Baake and Hans-Otto Georgii. Walter de Gruyter & Co., Berlin, 2008.</li>
</ul>

    
<h3>PhD Thesis</h3>

 <ul>
<li><strong>Stochastic processes in random environment</strong><br />
 PhD, University of Bath, 2009. <br />
 <a class="external-link" href="http://opus.bath.ac.uk/17911/">
PDF</a></li>
</ul>

My articles on: <a href="https://arxiv.org/a/ortgiese_m_1.html">arxiv</a>, <a href="https://mathscinet.ams.org/mathscinet/search/publications.html?pg1=INDI&s1=835679">MathSciNet</a>, <a href="https://scholar.google.co.uk/citations?hl=en&user=Uj2HxdAAAAAJ">Google Scholar</a>, <a href="https://orcid.org/0000-0001-7803-8584">Orcid</a>, <a href="https://researchportal.bath.ac.uk/en/persons/marcel-ortgiese/publications/">University of Bath researchportal</a>.


